<script>

</script>

<div>
    <table>
        <thead>
            <tr>
                <td>السورة</td>
                <td>ترتيب</td>
                <td>الآيات</td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>الفاتحة</td>
                <td>1</td>
                <td>7</td>
            </tr>
            <tr>
                <td>البقرة</td>
                <td>2</td>
                <td>286</td>
            </tr>
            <tr>
                <td>آل عمران</td>
                <td>3</td>
                <td>200</td>
            </tr>
            <tr>
                <td>النساء</td>
                <td>4</td>
                <td>176</td>
            </tr>
            <tr>
                <td>المائدة</td>
                <td>5</td>
                <td>120</td>
            </tr>
            <tr>
                <td>الأنعام</td>
                <td>6</td>
                <td>165</td>
            </tr>
            <tr>
                <td>الأعراف</td>
                <td>7</td>
                <td>206</td>
            </tr>
            <tr>
                <td>الأنفال</td>
                <td>8</td>
                <td>75</td>
            </tr>
            <tr>
                <td>التوبة</td>
                <td>9</td>
                <td>129</td>
            </tr>
            <tr>
                <td>يونس</td>
                <td>10</td>
                <td>109</td>
            </tr>
            <tr>
                <td>هود</td>
                <td>11</td>
                <td>123</td>
            </tr>
            <tr>
                <td>يوسف</td>
                <td>12</td>
                <td>111</td>
            </tr>
            <tr>
                <td>الرعد</td>
                <td>13</td>
                <td>43</td>
            </tr>
            <tr>
                <td>إبراهيم</td>
                <td>14</td>
                <td>52</td>
            </tr>
            <tr>
                <td>الحجر</td>
                <td>15</td>
                <td>99</td>
            </tr>
            <tr>
                <td>النحل</td>
                <td>16</td>
                <td>128</td>
            </tr>
            <tr>
                <td>الإسراء</td>
                <td>17</td>
                <td>111</td>
            </tr>
            <tr>
                <td>الكهف</td>
                <td>18</td>
                <td>110</td>
            </tr>
            <tr>
                <td>مريم</td>
                <td>19</td>
                <td>98</td>
            </tr>
            <tr>
                <td>طه</td>
                <td>20</td>
                <td>135</td>
            </tr>
            <tr>
                <td>الأنبياء</td>
                <td>21</td>
                <td>112</td>
            </tr>
            <tr>
                <td>الحج</td>
                <td>22</td>
                <td>78</td>
            </tr>
            <tr>
                <td>المؤمنون</td>
                <td>23</td>
                <td>118</td>
            </tr>
            <tr>
                <td>النور</td>
                <td>24</td>
                <td>64</td>
            </tr>
            <tr>
                <td>الفرقان</td>
                <td>25</td>
                <td>77</td>
            </tr>
            <tr>
                <td>الشعراء</td>
                <td>26</td>
                <td>227</td>
            </tr>
            <tr>
                <td>النمل</td>
                <td>27</td>
                <td>93</td>
            </tr>
            <tr>
                <td>القصص</td>
                <td>28</td>
                <td>88</td>
            </tr>
            <tr>
                <td>العنكبوت</td>
                <td>29</td>
                <td>69</td>
            </tr>
            <tr>
                <td>الروم</td>
                <td>30</td>
                <td>60</td>
            </tr>
            <tr>
                <td>لقمان</td>
                <td>31</td>
                <td>34</td>
            </tr>
            <tr>
                <td>السجدة</td>
                <td>32</td>
                <td>30</td>
            </tr>
            <tr>
                <td>الأحزاب</td>
                <td>33</td>
                <td>73</td>
            </tr>
            <tr>
                <td>سبأ</td>
                <td>34</td>
                <td>54</td>
            </tr>
            <tr>
                <td>فاطر</td>
                <td>35</td>
                <td>45</td>
            </tr>
            <tr>
                <td>يس</td>
                <td>36</td>
                <td>83</td>
            </tr>
            <tr>
                <td>الصافات</td>
                <td>37</td>
                <td>182</td>
            </tr>
            <tr>
                <td>ص</td>
                <td>38</td>
                <td>88</td>
            </tr>
            <tr>
                <td>الزمر</td>
                <td>39</td>
                <td>75</td>
            </tr>
            <tr>
                <td>غافر</td>
                <td>40</td>
                <td>85</td>
            </tr>
            <tr>
                <td>فصلت</td>
                <td>41</td>
                <td>54</td>
            </tr>
            <tr>
                <td>الشورى</td>
                <td>42</td>
                <td>53</td>
            </tr>
            <tr>
                <td>الزخرف</td>
                <td>43</td>
                <td>89</td>
            </tr>
            <tr>
                <td>الدخان</td>
                <td>44</td>
                <td>59</td>
            </tr>
            <tr>
                <td>الجاثية</td>
                <td>45</td>
                <td>37</td>
            </tr>
            <tr>
                <td>الأحقاف</td>
                <td>46</td>
                <td>35</td>
            </tr>
            <tr>
                <td>محمد</td>
                <td>47</td>
                <td>38</td>
            </tr>
            <tr>
                <td>الفتح</td>
                <td>48</td>
                <td>29</td>
            </tr>
            <tr>
                <td>الحجرات</td>
                <td>49</td>
                <td>18</td>
            </tr>
            <tr>
                <td>ق</td>
                <td>50</td>
                <td>45</td>
            </tr>
            <tr>
                <td>الذاريات</td>
                <td>51</td>
                <td>60</td>
            </tr>
            <tr>
                <td>الطور</td>
                <td>52</td>
                <td>49</td>
            </tr>
            <tr>
                <td>النجم</td>
                <td>53</td>
                <td>62</td>
            </tr>
            <tr>
                <td>القمر</td>
                <td>54</td>
                <td>55</td>
            </tr>
            <tr>
                <td>الرحمن</td>
                <td>55</td>
                <td>78</td>
            </tr>
            <tr>
                <td>الواقعة</td>
                <td>56</td>
                <td>96</td>
            </tr>
            <tr>
                <td>الحديد</td>
                <td>57</td>
                <td>29</td>
            </tr>
            <tr>
                <td>المجادلة</td>
                <td>58</td>
                <td>22</td>
            </tr>
            <tr>
                <td>الحشر</td>
                <td>59</td>
                <td>24</td>
            </tr>
            <tr>
                <td>الممتحنة</td>
                <td>60</td>
                <td>13</td>
            </tr>
            <tr>
                <td>الصف</td>
                <td>61</td>
                <td>14</td>
            </tr>
            <tr>
                <td>الجمعة</td>
                <td>62</td>
                <td>11</td>
            </tr>
            <tr>
                <td>المنافقون</td>
                <td>63</td>
                <td>11</td>
            </tr>
            <tr>
                <td>التغابن</td>
                <td>64</td>
                <td>18</td>
            </tr>
            <tr>
                <td>الطلاق</td>
                <td>65</td>
                <td>12</td>
            </tr>
            <tr>
                <td>التحريم</td>
                <td>66</td>
                <td>12</td>
            </tr>
            <tr>
                <td>الملك</td>
                <td>67</td>
                <td>30</td>
            </tr>
            <tr>
                <td>القلم</td>
                <td>68</td>
                <td>52</td>
            </tr>
            <tr>
                <td>الحاقة</td>
                <td>69</td>
                <td>52</td>
            </tr>
            <tr>
                <td>المعارج</td>
                <td>70</td>
                <td>44</td>
            </tr>
            <tr>
                <td>نوح</td>
                <td>71</td>
                <td>28</td>
            </tr>
            <tr>
                <td>الجن</td>
                <td>72</td>
                <td>28</td>
            </tr>
            <tr>
                <td>المزمل</td>
                <td>73</td>
                <td>20</td>
            </tr>
            <tr>
                <td>المدثر</td>
                <td>74</td>
                <td>56</td>
            </tr>
            <tr>
                <td>القيامة</td>
                <td>75</td>
                <td>40</td>
            </tr>
            <tr>
                <td>الإنسان</td>
                <td>76</td>
                <td>31</td>
            </tr>
            <tr>
                <td>المرسلات</td>
                <td>77</td>
                <td>50</td>
            </tr>
            <tr>
                <td>النبأ</td>
                <td>78</td>
                <td>40</td>
            </tr>
            <tr>
                <td>النازعات</td>
                <td>79</td>
                <td>46</td>
            </tr>
            <tr>
                <td>عبس</td>
                <td>80</td>
                <td>42</td>
            </tr>
            <tr>
                <td>التكوير</td>
                <td>81</td>
                <td>29</td>
            </tr>
            <tr>
                <td>الانفطار</td>
                <td>82</td>
                <td>19</td>
            </tr>
            <tr>
                <td>المطففين</td>
                <td>83</td>
                <td>36</td>
            </tr>
            <tr>
                <td>الانشقاق</td>
                <td>84</td>
                <td>25</td>
            </tr>
            <tr>
                <td>البروج</td>
                <td>85</td>
                <td>22</td>
            </tr>
            <tr>
                <td>الطارق</td>
                <td>86</td>
                <td>17</td>
            </tr>
            <tr>
                <td>الأعلى</td>
                <td>87</td>
                <td>19</td>
            </tr>
            <tr>
                <td>الغاشية</td>
                <td>88</td>
                <td>26</td>
            </tr>
            <tr>
                <td>الفجر</td>
                <td>89</td>
                <td>30</td>
            </tr>
            <tr>
                <td>البلد</td>
                <td>90</td>
                <td>20</td>
            </tr>
            <tr>
                <td>الشمس</td>
                <td>91</td>
                <td>15</td>
            </tr>
            <tr>
                <td>الليل</td>
                <td>92</td>
                <td>21</td>
            </tr>
            <tr>
                <td>الضحى</td>
                <td>93</td>
                <td>11</td>
            </tr>
            <tr>
                <td>الشرح</td>
                <td>94</td>
                <td>8</td>
            </tr>
            <tr>
                <td>التين</td>
                <td>95</td>
                <td>8</td>
            </tr>
            <tr>
                <td>العلق</td>
                <td>96</td>
                <td>19</td>
            </tr>
            <tr>
                <td>القدر</td>
                <td>97</td>
                <td>5</td>
            </tr>
            <tr>
                <td>البينة</td>
                <td>98</td>
                <td>8</td>
            </tr>
            <tr>
                <td>الزلزلة</td>
                <td>99</td>
                <td>8</td>
            </tr>
            <tr>
                <td>العاديات</td>
                <td>100</td>
                <td>11</td>
            </tr>
            <tr>
                <td>القارعة</td>
                <td>101</td>
                <td>11</td>
            </tr>
            <tr>
                <td>التكاثر</td>
                <td>102</td>
                <td>8</td>
            </tr>
            <tr>
                <td>العصر</td>
                <td>103</td>
                <td>3</td>
            </tr>
            <tr>
                <td>الهمزة</td>
                <td>104</td>
                <td>9</td>
            </tr>
            <tr>
                <td>الفيل</td>
                <td>105</td>
                <td>5</td>
            </tr>
            <tr>
                <td>قريش</td>
                <td>106</td>
                <td>4</td>
            </tr>
            <tr>
                <td>الماعون</td>
                <td>107</td>
                <td>7</td>
            </tr>
            <tr>
                <td>الكوثر</td>
                <td>108</td>
                <td>3</td>
            </tr>
            <tr>
                <td>الكافرون</td>
                <td>109</td>
                <td>6</td>
            </tr>
            <tr>
                <td>النصر</td>
                <td>110</td>
                <td>3</td>
            </tr>
            <tr>
                <td>المسد</td>
                <td>111</td>
                <td>5</td>
            </tr>
            <tr>
                <td>الإخلاص</td>
                <td>112</td>
                <td>4</td>
            </tr>
            <tr>
                <td>الفلق</td>
                <td>113</td>
                <td>5</td>
            </tr>
            <tr>
                <td>الناس</td>
                <td>114</td>
                <td>6</td>
            </tr>
        </tbody>
    </table></div>
<style>
div {
    
		max-height: 400px;
		overflow:auto;
}
td {
    text-align: right;
    padding: 2px;
}
</style>